name: Merge PR to main and website-main

on:
  pull_request:
    types: [closed]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git checkout main
          git pull origin main
          git merge ${{ github.event.pull_request.head.ref }}
          git push origin main

      - name: Check if demo-1 has changes
        run: |
          git fetch origin demo-1
          CHANGES=$(git rev-list --count HEAD..origin/demo-1)
          if [ "$CHANGES" -gt "0" ]; then
            echo "demo-1 has changes. Merging changes from main."
            git checkout demo-1
            git checkout main -- web/
            git add -A web/
            git commit -m "Merge web folder from main branch"
            git push origin demo-1
          else
            echo "demo-1 has no changes. Skipping merge."
          fi
