name: Merge with Demo-1 Check

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge web branch to demo-1
        run: |
          git fetch origin
          git checkout origin/demo-1
          git pull origin demo-1
          git diff --name-only web...demo-1 web/ | xargs -I {} git checkout origin/demo-1 -- {}
          git merge origin/web
          git push origin HEAD:demo-1

      - name: Merge web branch to demo-2
        run: |
          echo "----------Create a temporary directory to store contents of admin from origin/web branch"
          mkdir temp_main_admin
          echo "----------Checkout contents of admin from origin/web branch into the temporary directory"
          git checkout origin/web -- admin/* temp_main_admin/
          echo "----------Checkout demo-2"
          git checkout origin/demo-2
          echo "----------Compare contents of admin between origin/web and demo-2"
          git diff --name-only origin/web...origin/demo-2 admin/ | while read line; do rm -rf "$line"; done
          echo "----------Move back contents of admin from the temporary directory to admin"
          mv temp_main_admin/* admin/
          echo "----------Remove temporary directory"
          rm -rf temp_main_admin
          echo "----------Add and commit changes"
          git add .
          echo "----------Merge changes from origin/web into demo-2"
          git merge origin/web
          git push origin demo-2
