name: Merge with Demo-1 Check

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge web branch to demo-1
        run: |
          git fetch origin
          git checkout origin/demo-1
          git merge origin/web
          git push origin demo-1
