name: Merge with Demo-1 Check

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get PR branch name
        id: branch_name
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Get list of files in web folder in website branch
        id: website_web_files
        run: |
          git ls-tree -r --name-only HEAD web/
          echo "::set-output name=web_files::$(git ls-tree -r --name-only HEAD web/)"

      - name: Get list of files in web folder in demo-1 branch
        id: demo_1_web_files
        run: |
          git fetch origin demo-1
          git ls-tree -r --name-only origin/demo-1 web/
          echo "::set-output name=demo_1_web_files::$(git ls-tree -r --name-only origin/demo-1 web/)"

      - name: Compare web folder files between website and demo-1 branches
        id: compare_web_folders
        run: |
          if [ "${{ steps.website_web_files.outputs.web_files }}" = "${{ steps.demo_1_web_files.outputs.demo_1_web_files }}" ]; then
            echo "No changes in web folder files between website and demo-1 branches."
            echo "::set-output name=web_folder_changes::false"
          else
            echo "Changes found in web folder files between website and demo-1 branches."
            echo "::set-output name=web_folder_changes::true"
          fi
      
       - name: Merge PR into main and update demo-1
        run: |
          git fetch origin ${{ steps.branch_name.outputs.branch }}
          git merge --no-ff --no-edit ${{ steps.branch_name.outputs.branch }}
          if [[ steps.compare_web_folders.outputs.web_folder_changes == 'true' ]]; then
            git push origin HEAD:demo-1
          fi
