name: Merge with Demo-1 Check

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Merge web branch to demo-1
      #   run: |
      #     git fetch origin
      #     git checkout origin/demo-1
      #     git pull origin demo-1
      #     git diff --name-only web...demo-1 web/ | xargs -I {} git checkout origin/demo-1 -- {}
      #     git merge origin/web
      #     git push origin HEAD:demo-1

      - name: Merge web branch to demo-2
        run: |
          if [ "$(git diff --ignore-space-at-eol web:admin/ origin/demo-2:admin/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff web:admin/ origin/demo-2:admin/
          fi

