name: Auto Merge PR

on:
  pull_request:
    branches:
      - main  # Change to your main branch name

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Merge PR into demo-1
        run: git fetch origin ${{ github.event.pull_request.head.ref }} && git merge --no-ff --no-edit ${{ github.event.pull_request.head.ref }} -m "Auto-merging PR #${{ github.event.pull_request.number }}"
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'demo-1'
