name: Merge PR to main and website-main

on:
  pull_request:
    types: [closed]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git checkout main
          git pull origin main
          git merge ${{ github.event.pull_request.head.ref }}
          git push origin main

      - name: Check if website-main has changes
        run: |
          git fetch origin website-main
          CHANGES=$(git rev-list --count HEAD..origin/website-main)
          if [ "$CHANGES" -gt "0" ]; then
            echo "Website-main has changes. Merging changes from main."
            git checkout website-main
            git checkout main -- web/
            git add -A web/
            git commit -m "Merge web folder from main branch"
            git push origin website-main
          else
            echo "Website-main has no changes. Skipping merge."
          fi
