name: Merge with Folder Check

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get PR branch name
        id: branch_name
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Check for changes in web folder in demo-1 branch
        id: check_web_folder_demo_1
        run: |
          git fetch origin demo-1
          if [[ -n $(git diff --name-only demo-1..$branch_name | grep '^web/') ]]; then
            echo "Web folder has changes in demo-1 branch."
            echo "::set-output name=demo_1_web_changes::true"
          else
            echo "No changes in web folder in demo-1 branch."
            echo "::set-output name=demo_1_web_changes::false"
          fi
