name: Merge PR to main and website-main

on:
  pull_request:
    types: [closed]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git checkout main
          git pull origin main
          git merge ${{ github.event.pull_request.head.ref }}
          git push origin main

      - name: Check if demo-1 is ahead of main
        run: |
          git fetch origin main
          git fetch origin demo-1
          git checkout main
          if git merge-base --is-ancestor demo-1 main; then
            echo "Demo 1 is ahead of main. Merging changes from main."
            git checkout demo-1
            git merge main
            git push origin demo-1
          else
            echo "No changes to merge into demo-1."
          fi
