name: Merge with Demo-1 Check

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get PR branch name
        id: branch_name
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Check for changes in web folder in demo-1 branch
          id: check_web_folder_demo_1
          run: |
            git fetch origin demo-1
            git checkout demo-1
            if [[ $(git diff --name-only ${{ steps.branch_name.outputs.branch }} -- web/) ]]; then
              echo "Web folder files differ in demo-1 branch."
              echo "::set-output name=demo_1_web_changes::true"
            else
              echo "No changes in web folder files in demo-1 branch."
              echo "::set-output name=demo_1_web_changes::false"
            fi
