name: Merge with Demo-1 Check

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge web branch to demo-1
        run: |
          git fetch origin
          if [ "$(git diff --ignore-space-at-eol origin/web:web/ origin/demo-1 | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff origin/web:web/ origin/demo-1
          fi

      - name: Merge web branch to demo-2
        run: |
          git fetch origin
          if [ "$(git diff --ignore-space-at-eol origin/web:admin/ origin/demo-2 | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff origin/web:admin/ origin/demo-2
          fi

