name: Merge with Demo-1 Check

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch demo-1 branch
        run: git fetch origin demo-1:demo-1

      - name: Checkout demo-1 branch
        run: git checkout demo-1

      - name: Merge web branch to demo-1
        run: |
          git merge --no-ff --no-commit origin/web
          git commit -m "Merge changes from web branch"
          git push origin demo-1
