name: Merge with Demo-1 Check

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge web branch to demo-1
        run: |
          git fetch origin
          if [ "$(git diff origin/web:web origin/demo-1 | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes in the web folder after build. Pushing changes to demo-1 branch."
            git checkout demo-1
            git checkout web -- web
            git mv web/* .
            rm -r web
            git add .
            git commit -m "Update web folder contents"
            git push origin demo-1
          else
            echo "No changes detected in the web folder after build. Exiting."
          fi

      - name: Merge admin branch to demo-2
        run: |
          git fetch origin
          if [ "$(git diff origin/web:admin origin/demo-2 | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes in the admin folder after build. Pushing changes to demo-2 branch."
            git checkout demo-2
            git checkout web -- admin
            git mv admin/* .
            rm -r admin
            git add .
            git commit -m "Update admin folder contents"
            git push origin demo-2
          else
            echo "No changes detected in the admin folder after build. Exiting."
          fi
