name: Merge with Demo-1 Check

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch demo-1 branch
        run: git fetch origin demo-1:demo-1

      - name: Checkout demo-1 branch
        run: git checkout demo-1

      - name: Merge web branch to demo-1
        run: |
          git checkout demo-1
          git fetch origin
          git pull origin demo-1
          git checkout origin/web -- web/
          git checkout demo-1
          git merge origin/web --no-edit
          git push origin demo-1

      - name: Merge web branch to demo-2
        run: |
          git checkout demo-2
          git fetch origin
          git pull origin demo-2
          git checkout origin/web -- admin/
          git checkout demo-2
          git merge origin/web --no-edit
          git push origin demo-2
