name: Merge with Demo-1 Check

on:
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge web branch to demo-1
        run: |
          git fetch origin
          git checkout origin/demo-1
          git pull origin demo-1
          git diff --name-only web...demo-1 web/ | xargs -I {} git checkout origin/demo-1 -- {}
          git merge origin/web
          git push origin HEAD:demo-1

      - name: Merge web branch to demo-2
        run: |
          git fetch origin
          git checkout origin/demo-2
          git pull origin demo-2
          echo "------------------------Check out the contents of admin from origin/web branch to a temporary directory"
          git checkout origin/web -- admin/
          echo "------------------------Check out the contents of admin from demo-2 to a temporary directory"
          git checkout origin/demo-2
          echo "------------------------Diff the contents of admin between origin/web and demo-2"
          git diff --name-only admin/ origin/demo-2 | xargs -I {} git checkout origin/web -- {}
          echo "------------------------Add and commit changes"
          git add .
          echo "------------------------Merge changes from origin/web into demo-2"
          git merge origin/web
          git push origin HEAD:demo-2
